# SPDX-FileCopyrightText: 2021 Tuomas Siipola
# SPDX-License-Identifier: CC0-1.0

name: Docs
on:
  push:
    branches:
      - master
    # tags:
    #   - '*'
jobs:
  docs:
    runs-on: 'ubuntu-latest'
    container:
      image: phpdoc/phpdoc:3
      volumes:
        - ${{ github.workspace }}:/data
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: phpDocumentor
      run: phpdoc run -d src -t docs
    - name: Commit
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout -b gh-pages
        git add -f docs
        git commit -m "generated"
        git filter-branch --prune-empty --subdirectory-filter docs gh-pages
        git push origin gh-pages -f
